package com.javatrap2020_full_examples_java_collections;

public enum NamesEnum {
    ITERABLE, COLLECTION, COLLECTION_SET,
    COLLECTION_SET_HASH_SET, COLLECTION_SET_LINKED_HASH_SET,
    COLLECTION_SET_TREE_SET, COLLECTION_LIST, COLLECTION_LIST_ARRAY_LIST,
    COLLECTION_LIST_LINKED_LIST, COLLECTION_LIST_VECTOR,
    COLLECTION_LIST_VECTOR_STACK, COLLECTION_QUEUE_PRIORITY_QUEUE,
    COLLECTION_DEQUE_ARRAY_DEQUE, MAP_HASH_MAP, MAP_LINKED_HASH_MAP,
    MAP_TREE_MAP

}
